buildpack:
  gradle:
    id: org.springframework.boot
    version: 4.1.0
    default-task: paketo-base
    repository: gradlePluginPortal()
    description: |
      Plugin for OCI image generation using Cloud Native Buildpacks
    tasks:
      paketo-base: bootBuildImage
      tanzu-lite:
        - bootBuildImage
        - --builder=tanzu-build.packages.broadcom.com/tanzu-java-buildpack/java-lite
      tanzu-full:
        - bootBuildImage
        - --builder=tanzu-build.packages.broadcom.com/tanzu-java-buildpack/java
  maven:
    id: org.springframework.boot:spring-boot-maven-plugin
    version: 4.1.0
    default-task: paketo-base
    description: |
      Plugin for OCI image generation using Cloud Native Buildpacks
    tasks:
      paketo-base: :build-image
      tanzu-lite:
        - :build-image
        - --builder=tanzu-build.packages.broadcom.com/tanzu-java-buildpack/java-lite
      tanzu-full:
        - :build-image
        - --builder=tanzu-build.packages.broadcom.com/tanzu-java-buildpack/java